import { Metadata } from "next";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = {
  title: siteConfig.name,
  description: siteConfig.description,
  keywords: [
    "Sequence3",
    "AI",
    "AI Agent",
    "Agentic AI",
    "Explainable AI",
    "XAI",
    "Human-in-the-loop",
    "AI Automation",
    "Conversation AI",
    "Customer Experience",
    "Unified Inbox",
    "SME Tools",
    "Business Automation",
    "Intent Detection",
    "Sentiment Analysis",
    "AI Reasoning",
    "Customer Segmentation",
    "Workflow Automation",
    "Chat Automation",
    "Omnichannel Messaging",
    "Instagram DM Automation",
    "Facebook Inbox Automation",
    "WhatsApp Automation",
    "Knowledge Retrieval",
    "RAG",
    "Freelancer",
    "UI/UX",
    "Developer",
    "Frontend Developer",
    "Fullstack Developer",
    "React",
    "Next.js",
    "TypeScript",
    "Tailwind",
    "Tailwind CSS",
    "Tailwind V4",
    "Shadcn",
    "Shadcn UI",
    "Framer Motion",
    "Motion",
    "Design Systems",
    "SaaS",
    "Startup Tools",
    "Team Collaboration",
    "Productivity Tools",
    "Automation Software",
    "Business Messaging",
    "Customer Support AI",
    "Digital Assistants",
    "AI-powered Workflows",
    "Tech Startup",
    "Modern Web Apps",
    "Next.js SaaS",
    "Modern UI Components"
  ],
  authors: [
    {
      name: "Sequence3",
      url: "https://sequence3.se",
    },
  ],
  creator: "Sequence3",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    title: siteConfig.name,
    description: siteConfig.description,
    siteName: siteConfig.name,
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    creator: "@sequence3",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};
